apiVersion: v1
kind: Service
metadata:
  name: redis-0
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-0
  selector:
    statefulset.kubernetes.io/pod-name: redis-0
---

apiVersion: v1
kind: Service
metadata:
  name: redis-1
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-1
  selector:
    statefulset.kubernetes.io/pod-name: redis-1
---
apiVersion: v1
kind: Service
metadata:
  name: redis-2
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-2
  selector:
    statefulset.kubernetes.io/pod-name: redis-2
---



